#
# This test file has been generated by kwb.test::create_test_files()
# launched by user micha on 2020-09-30 01:12:45.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that(".stopOnNoMatchingIDAtAll() works", {

  expect_error(
    kwb.epanet:::.stopOnNoMatchingIDAtAll()
    # konnte Funktion "catIf" nicht finden
  )

})

