#
# *** This file was generated by toRoxygen.R.
# *** DO NOT EDIT!
#

# getPipeCoordinates -----------------------------------------------------------

#' getPipeCoordinates
#' 
#' getPipeCoordinates
#' 
getPipeCoordinates <- function # getPipeCoordinates
### getPipeCoordinates
(
  inpdat
)
{
  x <- inpdat$PIPES[, c("ID", "Node1", "Node2")]
  x <- merge(x, inpdat$COORDINATES, by.x="Node1", by.y="Node")
  x <- hsRenameColumns(x, list(X_Coord="Node1.x", Y_Coord="Node1.y"))
  x <- merge(x, inpdat$COORDINATES, by.x="Node2", by.y="Node")
  x <- hsRenameColumns(x, list(X_Coord="Node2.x", Y_Coord="Node2.y"))
  rownames(x) <- x$ID
  
  numericColumns <- c("Node1.x", "Node1.y", "Node2.x", "Node2.y")

  for (col in numericColumns) {
    x[[col]] <- as.numeric(x[[col]])
  }
    
  x[, c("Node1", "Node2", numericColumns)]
}

# getPumpInfo ------------------------------------------------------------------

#' getPumpInfo
#' 
#' getPumpInfo
#' 
getPumpInfo <- function # getPumpInfo
### getPumpInfo
(
  inpdat
)
{
  pumpinfo <- merge(inpdat$PUMPS, inpdat$COORDINATES, by.x="Node1", by.y="Node")
  pumpinfo <- hsRenameColumns(pumpinfo, list(X_Coord = "Node1.x", Y_Coord = "Node1.y"))
  rownames(pumpinfo) <- pumpinfo$ID

  pumpinfo$Node1.x <- as.numeric(pumpinfo$Node1.x)
  pumpinfo$Node1.y <- as.numeric(pumpinfo$Node1.y)
  
  pumpinfo[, c("Node1", "Node2", "Node1.x", "Node1.y", "Parameters")]
}

# getNamesOfObjects ------------------------------------------------------------

#' getNamesOfObjects
#' 
#' getNamesOfObjects
#' 
getNamesOfObjects <- function # getNamesOfObjects
### getNamesOfObjects
(
  inpdat, 
  section, 
  pattern = ".*"
)
{
  grep(pattern, unique(inpdat[[section]]$ID), value=TRUE)
}

# getNamesOfCurves -------------------------------------------------------------

#' getNamesOfCurves
#' 
#' getNamesOfCurves
#' 
getNamesOfCurves <- function # getNamesOfCurves
### getNamesOfCurves
(
  inpdat, 
  pattern = ".*"
)
{
  getNamesOfObjects(inpdat, "CURVES", pattern)  
}

# getNamesOfJunctions ----------------------------------------------------------

#' getNamesOfJunctions
#' 
#' getNamesOfJunctions
#' 
getNamesOfJunctions <- function # getNamesOfJunctions
### getNamesOfJunctions
(
  inpdat, 
  pattern = ".*"
)
{
  getNamesOfObjects(inpdat, "JUNCTIONS", pattern)  
}

# getNamesOfReservoirs ---------------------------------------------------------

#' getNamesOfReservoirs
#' 
#' getNamesOfReservoirs
#' 
getNamesOfReservoirs <- function # getNamesOfReservoirs
### getNamesOfReservoirs
(
  inpdat, 
  pattern = ".*"
)
{
  getNamesOfObjects(inpdat, "RESERVOIRS", pattern)  
}

# getNamesOfTanks --------------------------------------------------------------

#' getNamesOfTanks
#' 
#' getNamesOfTanks
#' 
getNamesOfTanks <- function # getNamesOfTanks
### getNamesOfTanks
(
  inpdat, 
  pattern = ".*"
)
{
  getNamesOfObjects(inpdat, "TANKS", pattern)  
}

# getNamesOfPipes --------------------------------------------------------------

#' getNamesOfPipes
#' 
#' getNamesOfPipes
#' 
getNamesOfPipes <- function # getNamesOfPipes
### getNamesOfPipes
(
  inpdat, 
  pattern = ".*"
)
{
  getNamesOfObjects(inpdat, "PIPES", pattern)  
}

# getNamesOfPumps --------------------------------------------------------------

#' getNamesOfPumps
#' 
#' getNamesOfPumps
#' 
getNamesOfPumps <- function # getNamesOfPumps
### getNamesOfPumps
(
  inpdat, 
  pattern = ".*"
)
{
  getNamesOfObjects(inpdat, "PUMPS", pattern)  
}

# getNamesOfValves -------------------------------------------------------------

#' getNamesOfValves
#' 
#' getNamesOfValves
#' 
getNamesOfValves <- function # getNamesOfValves
### getNamesOfValves
(
  inpdat, 
  pattern = ".*"
)
{
  getNamesOfObjects(inpdat, "VALVES", pattern)  
}
